# Generated by Django 2.2 on 2020-09-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_ingredient_recipe_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recipe_app.Recipe'),
        ),
    ]
